name: ci

concurrency:
  group: ci-${{ github.head_ref }}
  # In order to save GitHub Actions usage, we are canceling the running action
  # of the previous commit. This means, if you first push commit "A" and after a
  # few minutes commit "B" to the pull request, the workflow run for commit "A"
  # will be canceled.
  cancel-in-progress: true

on:
  # We need to use "pull_request_target" instead of "pull_request" because we
  # all have no repository access. And because we have no repository access and
  # this action is using a secret, would run the action the with "pull_request"
  # with base branch.
  pull_request_target:
    # The types trigger are needed to prevent github running our action when a
    # pull request is marked as draft:
    # https://github.community/t/dont-run-actions-on-draft-pull-requests/16817/16
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  # This workflow applies labels to pull requests based on the paths that are
  # modified in the pull request.
  #
  # Edit `.github/labeler.yml` to configure labels.
  #
  # For more information, see: https://github.com/actions/labeler
  label-pr:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v3
      - name: Label PR
        uses: actions/labeler@v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
